target("NuiTest")
    set_default(true)
    set_kind("shared")
    add_files("**.cpp")
    add_headerfiles("**.h")
    add_includedirs("$(projectdir)/Engine/")
    add_links("NuiCore", "NuiGraphics", "User32.lib")
    add_deps("NuiCore", "NuiGraphics")
    add_linkorders("User32.lib", "NuiCore", "NuiGraphics")
    set_group("Nui")