target("NuiCore")
    set_default(false)
    set_kind("static")
    add_files("**.cpp")
    add_headerfiles("**.h")
    add_extrafiles("$(projectdir)/Engine/External/DirectXTK.inl")
    add_includedirs("$(scriptdir)/Engine/")
    add_links("NuiGraphics", "User32.lib")
    add_deps("NuiGraphics")
    set_group("Nui")
