rule("HLSL")
	set_extensions(".hlsl")
	on_build_file(function (target, sourcefile, opt)
        print("Shader file: " .. sourcefile)
    end)
rule_end()

target("NuiGraphics")
    set_default(false)
    set_kind("static")
    --add_rules("HLSL")
    add_rules("utils.bin2c", {extensions = {".hlsl"}})
    add_files("**.cpp")
    add_files("Shaders/*.hlsl")
    add_headerfiles("**.h")
    add_includedirs("$(scriptdir)/Engine/")
    add_links("User32.lib")
    set_group("Nui")
target_end()
