name: Generate CMakeLists.txt with xmake

on:
    push:
        branches:
            - main

jobs:
    generate-cmake:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up xmake
              uses: xmake-io/github-action-setup-xmake@v1
              with:
                  xmake-version: latest

            - name: Generate CMakeLists.txt
              run: |
                  echo Workspace: ${GITHUB_WORKSPACE}
                  xmake project --file=${GITHUB_WORKSPACE}/xmake.lua -k cmakelists -a "x64"

            - name: Commit and push changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add CMakeLists.txt
                  git commit -m "Auto-generate CMakeLists.txt"
                  git push origin main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
