name: Generate CMakeLists.txt with xmake

on:
    push:
        branches:
            - main

jobs:
    generate-cmake:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # - name: Set up xmake
            #   uses: xmake-io/github-action-setup-xmake@v1
            #   with:
            #       xmake-version: latest
            #       actions-cache-folder: ".xmake-cache"

            # xmake project --file=./xmake.lua -k cmakelists
            - name: Generate CMakeLists.txt
              run: |
                  echo Workspace: ${GITHUB_WORKSPACE}

            - name: Commit and push changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add CMakeLists.txt
                  git commit -m "Auto-generate CMakeLists.txt"
                  git push origin main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
